#!/bin/sh
#
# Xcode Cloud post-clone hook. Xcode Cloud runs this once, right after it clones
# the repository and before it resolves Swift packages or starts xcodebuild.
#
# Two Qwave-specific reasons this is REQUIRED — a bare clone will not build
# without it:
#
#   1. Qwave.xcodeproj is generated by XcodeGen from project.yml (the single
#      source of truth) and is gitignored. A fresh Xcode Cloud clone therefore
#      contains no .xcodeproj/.xcworkspace to build until we generate it here.
#
#   2. The PacketTunnel system extension links a Zig static library
#      (libqpacket.a) and a WireGuard Go bridge (libwg-go.a). Those are produced
#      by the target's preBuildScripts during xcodebuild, which hard-error if
#      `zig` / `go` are missing from PATH.
#
# This mirrors the toolchain install + generate step in
# .github/workflows/ci.yml (`brew install xcodegen zig go` -> `xcodegen generate`).
# See docs/XCODE_CLOUD.md for the workflow setup this script enables.

set -e

export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

echo "==> [ci_post_clone] Installing build toolchains: xcodegen, zig, go"
brew install xcodegen zig go

# Xcode Cloud starts this script in the ci_scripts/ directory; move to the repo
# root so xcodegen writes Qwave.xcodeproj next to project.yml.
cd "${CI_PRIMARY_REPOSITORY_PATH:-${CI_WORKSPACE:-$(dirname "$0")/..}}"

echo "==> [ci_post_clone] Generating Qwave.xcodeproj from project.yml"
xcodegen generate --spec project.yml

echo "==> [ci_post_clone] Done. zig=$(zig version 2>/dev/null) go=$(go version 2>/dev/null)"
