import XCTest
@testable import PostQuantum

/// Hybrid (ML-KEM-768 + Classic McEliece 348864) KEM tests: known-answer
/// vectors generated by the Python oracle, plus behavioural properties.
final class HybridKEMTests: XCTestCase {
    private struct Vector: Decodable {
        let name: String
        let seed: String
        let ek: String
        let dk: String
        let ct: String
        let ss: String
    }

    private var vectors: [Vector] = []

    override func setUpWithError() throws {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "hybrid_vectors", withExtension: "json"))
        let data = try Data(contentsOf: url)
        vectors = try JSONDecoder().decode([Vector].self, from: data)
    }

    private func unhex(_ s: String) -> Data {
        var data = Data()
        var index = s.startIndex
        while index < s.endIndex {
            let next = s.index(index, offsetBy: 2)
            data.append(UInt8(s[index..<next], radix: 16)!)
            index = next
        }
        return data
    }

    func testKeygenMatchesVectors() throws {
        for v in vectors {
            let (ek, dk) = try HybridKEM.keygen(seed: unhex(v.seed))
            XCTAssertEqual(ek, unhex(v.ek), "\(v.name) ek mismatch")
            XCTAssertEqual(dk, unhex(v.dk), "\(v.name) dk mismatch")
        }
    }

    func testEncapsMatchesVectors() throws {
        for v in vectors {
            let (ct, ss) = try HybridKEM.encapsulate(ek: unhex(v.ek), seed: unhex(v.seed))
            XCTAssertEqual(ct, unhex(v.ct), "\(v.name) ct mismatch")
            XCTAssertEqual(ss, unhex(v.ss), "\(v.name) ss mismatch")
        }
    }

    func testDecapsMatchesVectors() throws {
        for v in vectors {
            let ss = try HybridKEM.decapsulate(dk: unhex(v.dk), ct: unhex(v.ct))
            XCTAssertEqual(ss, unhex(v.ss), "\(v.name) decaps mismatch")
        }
    }

    func testKeySizes() {
        XCTAssertEqual(HybridKEM.ekSize, 262_304)
        XCTAssertEqual(HybridKEM.dkSize, 7_730)
        XCTAssertEqual(HybridKEM.ctSize, 1_524)
        XCTAssertEqual(HybridKEM.ssSize, 32)
    }

    func testFullFlowRoundTrip() throws {
        let seed = Data((0..<32).map { UInt8(($0 * 17 + 5) % 251) })
        let (ek, dk) = try HybridKEM.keygen(seed: seed)
        let (ct, ss) = try HybridKEM.encapsulate(ek: ek, seed: seed)
        let ss2 = try HybridKEM.decapsulate(dk: dk, ct: ct)
        XCTAssertEqual(ss2, ss)
    }

    func testWrongKeyFails() throws {
        let (ek, _) = try HybridKEM.keygen(seed: Data(repeating: 0x01, count: 32))
        let (_, wrongDk) = try HybridKEM.keygen(seed: Data(repeating: 0x02, count: 32))
        let (ct, _) = try HybridKEM.encapsulate(ek: ek, seed: Data(repeating: 0x03, count: 32))
        // the McEliece leg's codeword verification rejects a wrong key
        XCTAssertThrowsError(try HybridKEM.decapsulate(dk: wrongDk, ct: ct))
    }

    func testDifferentSeedsDiffer() throws {
        let seedA = Data(repeating: 0xAA, count: 32)
        let seedB = Data(repeating: 0xBB, count: 32)
        let (ekA, dkA) = try HybridKEM.keygen(seed: seedA)
        let (ekB, _) = try HybridKEM.keygen(seed: seedB)
        XCTAssertNotEqual(ekA, ekB)
        let (ctA, ssA) = try HybridKEM.encapsulate(ek: ekA, seed: seedA)
        let (ctB, ssB) = try HybridKEM.encapsulate(ek: ekB, seed: seedB)
        XCTAssertNotEqual(ctA, ctB)
        XCTAssertNotEqual(ssA, ssB)
        XCTAssertEqual(try HybridKEM.decapsulate(dk: dkA, ct: ctA), ssA)
    }
}
