import Foundation
import WebKit
import QwaveSupport

public enum RuleListError: Error {
    case missingResource(String)
    case compilationReturnedNothing
}

/// Compiles the bundled content-blocker rule sets into `WKContentRuleList`s.
/// Compiled lists are cached by WebKit keyed on identifier; the identifier
/// embeds a hash of the JSON so editing a shipped list invalidates the cache.
@MainActor
public final class RuleListCompiler {
    public enum BuiltinList: String, CaseIterable, Sendable {
        /// EasyList-scale snapshot regenerated by scripts/update-blocklist.sh
        /// (see docs/BLOCKLIST.md for the pipeline and license boundary).
        case adsAndTrackers = "easylist-compiled"
        case httpsUpgrade = "https-upgrade"
    }

    private let store: WKContentRuleListStore
    private var cache: [BuiltinList: WKContentRuleList] = [:]

    public init(store: WKContentRuleListStore? = nil) {
        self.store = store ?? .default()
    }

    public static func builtinJSON(for list: BuiltinList) throws -> String {
        guard let url = Bundle.module.url(forResource: list.rawValue, withExtension: "json") else {
            throw RuleListError.missingResource(list.rawValue)
        }
        return try String(contentsOf: url, encoding: .utf8)
    }

    public func compiledList(for list: BuiltinList) async throws -> WKContentRuleList {
        if let cached = cache[list] {
            return cached
        }
        let json = try Self.builtinJSON(for: list)
        let identifier = "\(list.rawValue)-\(Self.stableHash(of: json))"

        if let existing = try? await lookUp(identifier: identifier) {
            cache[list] = existing
            return existing
        }

        let compiled = try await compile(identifier: identifier, json: json)
        cache[list] = compiled
        QwaveLog.shields.info("Compiled rule list \(identifier, privacy: .public)")
        return compiled
    }

    /// Launch-path variant: returns fast, shields active from the first
    /// paint. Cache hit → that list. Cache miss with a previous version of
    /// the same list in the store (the identifier embeds a content hash, so
    /// an updated bundle changes it) → the STALE list is returned
    /// immediately and the fresh one compiles in the background;
    /// `onRefresh` delivers it and the superseded artifact is removed.
    /// True first launch (nothing to serve) → waits for the full compile,
    /// which is the correct trade for a shields-first browser.
    public func availableList(
        for list: BuiltinList,
        onRefresh: @escaping @MainActor (WKContentRuleList) -> Void
    ) async throws -> WKContentRuleList {
        if let cached = cache[list] {
            return cached
        }
        let json = try Self.builtinJSON(for: list)
        let identifier = "\(list.rawValue)-\(Self.stableHash(of: json))"

        if let existing = try? await lookUp(identifier: identifier) {
            cache[list] = existing
            return existing
        }

        let staleIdentifier = await availableIdentifiers()
            .first { $0.hasPrefix("\(list.rawValue)-") && $0 != identifier }
        if let staleIdentifier, let stale = try? await lookUp(identifier: staleIdentifier) {
            QwaveLog.shields.info(
                "Serving stale rule list \(staleIdentifier, privacy: .public) while \(identifier, privacy: .public) compiles"
            )
            Task { @MainActor [weak self] in
                guard let self else { return }
                do {
                    let fresh = try await self.compile(identifier: identifier, json: json)
                    self.cache[list] = fresh
                    self.store.removeContentRuleList(forIdentifier: staleIdentifier) { _ in }
                    QwaveLog.shields.info("Refreshed rule list \(identifier, privacy: .public)")
                    onRefresh(fresh)
                } catch {
                    QwaveLog.shields.error(
                        "Background rule refresh failed: \(error.localizedDescription, privacy: .public)")
                }
            }
            return stale
        }

        let compiled = try await compile(identifier: identifier, json: json)
        cache[list] = compiled
        QwaveLog.shields.info("Compiled rule list \(identifier, privacy: .public)")
        return compiled
    }

    private func availableIdentifiers() async -> [String] {
        await withCheckedContinuation { continuation in
            store.getAvailableContentRuleListIdentifiers { identifiers in
                continuation.resume(returning: identifiers ?? [])
            }
        }
    }

    private func lookUp(identifier: String) async throws -> WKContentRuleList? {
        try await withCheckedThrowingContinuation { continuation in
            store.lookUpContentRuleList(forIdentifier: identifier) { list, error in
                if let error {
                    continuation.resume(throwing: error)
                } else {
                    continuation.resume(returning: list)
                }
            }
        }
    }

    private func compile(identifier: String, json: String) async throws -> WKContentRuleList {
        try await withCheckedThrowingContinuation { continuation in
            store.compileContentRuleList(forIdentifier: identifier, encodedContentRuleList: json) { list, error in
                if let error {
                    continuation.resume(throwing: error)
                } else if let list {
                    continuation.resume(returning: list)
                } else {
                    continuation.resume(throwing: RuleListError.compilationReturnedNothing)
                }
            }
        }
    }

    /// FNV-1a — stable across launches, unlike `String.hashValue`.
    static func stableHash(of string: String) -> String {
        var hash: UInt64 = 0xcbf29ce484222325
        for byte in string.utf8 {
            hash ^= UInt64(byte)
            hash = hash &* 0x100000001b3
        }
        return String(hash, radix: 16)
    }
}
